/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.lakeareatech.cis238.pizza;

/**
 *
 * @author jeffrey.herold
 */
public class frmPizza extends javax.swing.JFrame {

    /**
     * Creates new form frmPizza
     */
    public frmPizza() {
        initComponents();
        this.radSmall.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radSmall = new javax.swing.JRadioButton();
        radMedium = new javax.swing.JRadioButton();
        radLarge = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        chkPepperoni = new javax.swing.JCheckBox();
        chkBacon = new javax.swing.JCheckBox();
        chkSausage = new javax.swing.JCheckBox();
        chkShrooms = new javax.swing.JCheckBox();
        chkOlives = new javax.swing.JCheckBox();
        chkOnions = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Crust Size");
        jLabel1.setOpaque(true);

        buttonGroup1.add(radSmall);
        radSmall.setText("Small");
        radSmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSmallActionPerformed(evt);
            }
        });

        buttonGroup1.add(radMedium);
        radMedium.setText("Medium");
        radMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMediumActionPerformed(evt);
            }
        });

        buttonGroup1.add(radLarge);
        radLarge.setText("Large");
        radLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radLargeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(radSmall)
                .addGap(18, 18, 18)
                .addComponent(radMedium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radLarge)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radSmall)
                    .addComponent(radMedium)
                    .addComponent(radLarge))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Toppings");
        jLabel2.setOpaque(true);

        chkPepperoni.setText("Pepperoni");
        chkPepperoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPepperoniActionPerformed(evt);
            }
        });

        chkBacon.setText("Canadian Bacon");
        chkBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBaconActionPerformed(evt);
            }
        });

        chkSausage.setText("Sausage");
        chkSausage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSausageActionPerformed(evt);
            }
        });

        chkShrooms.setText("Mushrooms");
        chkShrooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShroomsActionPerformed(evt);
            }
        });

        chkOlives.setText("Black Olives");
        chkOlives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOlivesActionPerformed(evt);
            }
        });

        chkOnions.setText("Onions");
        chkOnions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOnionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkPepperoni)
                    .addComponent(chkOlives))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkBacon)
                    .addComponent(chkShrooms))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkSausage)
                    .addComponent(chkOnions))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPepperoni)
                    .addComponent(chkBacon)
                    .addComponent(chkSausage))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkOnions)
                    .addComponent(chkOlives)
                    .addComponent(chkShrooms))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jLabel3.setText("Price:");

        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPrice.setText("0");
        lblPrice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnCalculate.setMnemonic('C');
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnClear.setMnemonic('l');
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setMnemonic('x');
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblPrice))
                    .addComponent(btnCalculate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Exit the program
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // Calculate crust price
        this.lblPrice.setText(String.valueOf(getCrustPrice(this.radSmall.isSelected(),
                                            this.radMedium.isSelected(), 
                                            this.radLarge.isSelected())+ getToppingPrice()));
        
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // Clear the form
        //default to small crust size
        this.radSmall.setSelected(true);
        
        //clear toppings
        this.chkPepperoni.setSelected(false);
        this.chkBacon.setSelected(false);
        this.chkSausage.setSelected(false);
        this.chkOlives.setSelected(false);
        this.chkShrooms.setSelected(false);
        this.chkOnions.setSelected(false);
        
        // reset price to zero
        resetPrice();
    }//GEN-LAST:event_btnClearActionPerformed

    private void radSmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSmallActionPerformed
        //reset price to zero
        resetPrice();
        
        //call calc button
        this.btnCalculate.doClick();
    }//GEN-LAST:event_radSmallActionPerformed

    private void radMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMediumActionPerformed
        //reset price to zero
        resetPrice();
        
        //call calc button
        this.btnCalculate.doClick();
    }//GEN-LAST:event_radMediumActionPerformed

    private void radLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLargeActionPerformed
        //reset price to zero
        resetPrice();
        
        //call calc button
        this.btnCalculate.doClick();
    }//GEN-LAST:event_radLargeActionPerformed

    private void chkPepperoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPepperoniActionPerformed
        //call calc button
        this.btnCalculate.doClick();
    }//GEN-LAST:event_chkPepperoniActionPerformed

    private void chkBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBaconActionPerformed
        //call calc button
        this.btnCalculate.doClick();
    }//GEN-LAST:event_chkBaconActionPerformed

    private void chkSausageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSausageActionPerformed
        //call calc button
        this.btnCalculate.doClick();
    }//GEN-LAST:event_chkSausageActionPerformed

    private void chkOlivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOlivesActionPerformed
        //call calc button
        this.btnCalculate.doClick();
    }//GEN-LAST:event_chkOlivesActionPerformed

    private void chkShroomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShroomsActionPerformed
        //call calc button
        this.btnCalculate.doClick();
    }//GEN-LAST:event_chkShroomsActionPerformed

    private void chkOnionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOnionsActionPerformed
        //call calc button
        this.btnCalculate.doClick();
    }//GEN-LAST:event_chkOnionsActionPerformed

    private void resetPrice()
    {
        this.lblPrice.setText("0");
    }
    
    private double getCrustPrice(boolean small, boolean medium, boolean large)
    {
        //initialize variable
        double dblPrice = 0;
        
        //if statements go here
        if (small)
        {
            dblPrice += 6.99;
        }
        else if (medium)
        {
            dblPrice += 10.99;
        }
        else if (large)
        {
            dblPrice += 16.99;
        }
        
        //return price
        return dblPrice;
    }
    
    private double getToppingPrice()
    {
        //initialize variables
        double dblPrice = 0;
        
        //add toppings
        if(this.chkPepperoni.isSelected())
        {
            dblPrice += 1.49;
        }
        if(this.chkBacon.isSelected())
        {
            dblPrice += 1.49;
        }
        if(this.chkSausage.isSelected())
        {
            dblPrice += 1.49;
        }
        if(this.chkOlives.isSelected())
        {
            dblPrice += 0.99;
        }
        if(this.chkShrooms.isSelected())
        {
            dblPrice += 0.99;
        }
        if(this.chkOnions.isSelected())
        {
            dblPrice += 0.99;
        }
        //return price
        return dblPrice;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPizza().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkBacon;
    private javax.swing.JCheckBox chkOlives;
    private javax.swing.JCheckBox chkOnions;
    private javax.swing.JCheckBox chkPepperoni;
    private javax.swing.JCheckBox chkSausage;
    private javax.swing.JCheckBox chkShrooms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JRadioButton radLarge;
    private javax.swing.JRadioButton radMedium;
    private javax.swing.JRadioButton radSmall;
    // End of variables declaration//GEN-END:variables
}
